name: Build and push narrative images

on:
  workflow_call:
    secrets:
      GHCR_USERNAME:
        required: true
      GHCR_TOKEN:
        required: true

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out GitHub Repo
      if: github.event.pull_request.draft == false
      with:
        ref: "${{ github.event.pull_request.head.sha }}"
      uses: actions/checkout@v2
    - name: Check Source Branch
      if: github.head_ref != 'develop' && (github.base_ref == 'master' || github.base_ref == 'main')
      run: echo "PRs must be made to develop branch before merging to main/master"; exit 1
    - name: Build And Push To Packages
      if: github.event.pull_request.draft == false && github.event.action != 'closed' && github.event.pull_request.merged != true
      env:
        PR: "${{ github.event.pull_request.number }}"
        SHA: "${{ github.event.pull_request.head.sha }}"
        DOCKER_ACTOR: "${{ secrets.GHCR_USERNAME }}"
        DOCKER_TOKEN: "${{ secrets.GHCR_TOKEN }}"
      shell: bash
      run: |
          export MY_ORG=$(echo "${GITHUB_REPOSITORY}" | awk -F / '{print tolower($1)}')
          export DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          export BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          export COMMIT=$(echo "$SHA" | cut -c -7)

          echo "Source branch is $GITHUB_HEAD_REF"
          echo "Target branch is $GITHUB_BASE_REF"

          if  [ "$GITHUB_BASE_REF" = "develop" ]; then
            export MY_APP=$(echo $(echo "${GITHUB_REPOSITORY}" | awk -F / '{print $2}')"-develop")
          elif [ "$GITHUB_BASE_REF" = "main" ] || [ "$GITHUB_BASE_REF" = "master" ]; then
            export MY_APP=$(echo "${GITHUB_REPOSITORY}" | awk -F / '{print $2}')
          else
            echo "Target branch must be develop, main, or master";
            exit 1
          fi

          if [[ ( $GITHUB_BASE_REF = "main"  || $GITHUB_BASE_REF = "master" ) && $GITHUB_HEAD_REF != "develop" ]]; then
            echo "Must merge PRs to develop before merging to main/master";
            exit 1
          else
            echo "$DOCKER_TOKEN" | docker login ghcr.io -u "$DOCKER_ACTOR" --password-stdin
            docker build --build-arg BUILD_DATE="$DATE" \
                        --build-arg COMMIT="$COMMIT" \
                        --build-arg BRANCH="$GITHUB_HEAD_REF" \
                        --build-arg PULL_REQUEST="$PR" \
                        --label us.kbase.vcs-commit="$COMMIT" \
                        --label us.kbase.vcs-pull-req="$PR" \
                        -t ghcr.io/"$MY_ORG"/"$MY_APP":"pr-""$PR" .
            docker push ghcr.io/"$MY_ORG"/"$MY_APP":"pr-""$PR"
          fi