---
name: PR to develop opened
on:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - reopened
      - synchronize
jobs:
  build:
    uses: kbase/.github/.github/workflows/reusable_build.yml@main
