---
name: Release - Test, Build & Push Image
on:
  release:
    branches:
      - main
      - master
    types: [ published ]
jobs:
  check-source-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check Source Branch
        if: github.event.release.target_commitish != 'master' && github.event.release.target_commitish != 'main'
        run: echo "Releases must be built from master/main branch"; exit 1
  validate-release-tag:
    uses: kbase/.github/.github/workflows/reusable_validate-release-tag.yml@main
    with:
      release_tag: '${{ github.event.release.tag_name }}'
  build-push:
    needs: validate-release-tag
    uses: kbase/.github/.github/workflows/reusable_build-push.yml@main
    with:
      name: '${{ github.event.repository.name }}'
      tags: '${{ github.event.release.tag_name }},latest'
    secrets: inherit
