---
name: Ensure releases are built from main/master branch.
on:
  workflow_call:
    inputs:
      build_branch:
        required: true
        type: string
jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Validate build branch
        uses: actions/github-script@v6
        with:
          script: |
            const buildBranch = '${{ inputs.build_branch }}';
            if ((buildBranch !== 'main') && ((buildBranch !== 'master')) {
              core.setFailed(`Releases must be built from the main or master branch, not "${buildBranch}"`)
            }
